### ISSUE TITLE
Input switch?

### ISSUE THREAD

**Issue by raphaelyancey** [hs65/Gnome-Shell-Extension-Audio-Selector#3]
Thanks for this simple yet very useful extension!

I was wondering if I should see the audio input switch? The extension says "input/output" but I can only switch the output.

Thanks again.

**Comment by hs65** [comment]
The input selector has to be enabled using the "Extension Preferences" - Is just a click on the option

For fedora 37 the extension is no longer needed


Am Mittwoch, dem 16.11.2022 um 07:34 -0800 schrieb Raphael Yancey:

**Comment by raphaelyancey** [comment]
Oops, missed that thanks.
